Product.create!([
  {name: "Begyle Brewing - Crash Landed", price: "2", image: "https://untappd.akamaized.net/photo/2016_01_06/d8fac9f17c3719ee3f5a70d4fb7b7b59_640x640.jpg", description: "Crash Landed is a happy American Pale Wheat Ale balanced by a slight sweetness!"},
  {name: "Pipeworks Brewing Co. - Ninja vs. Unicorn", price: "11.99", image: "http://beerimages.pintley.com/43666/Pipeworks%20Ninja%20Vs%20Unicorn_large.png", description: "Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%, Double IPA, ABV: 8.0%"},
  {name: "Pipeworks Brewing Co. - Paradisiac", price: "12.99", image: "http://static1.squarespace.com/static/523d035de4b0f99c83ed886d/t/53c6ab2be4b08f8f944f94ff/1405528875986/Paradisiac.jpg", description: "Witbier, ABV: 7.50%"},
  {name: "Half Acre - Pony Pilsner", price: "$9.99", image: "http://static1.squarespace.com/static/50edbe8fe4b0a16d22fca55c/t/51a4dbcfe4b040da1a86c5f3/1369758674267/Pony.jpg", description: "A German style pilsner brewed with American heft. Take a ride through this golden field of barley any time you want to taste the sun. 5.8% ABV - available year round."},
  {name: "Half Acre - Daisy Cutter", price: "$8.99", image: "http://www.theperfectlyhappyman.com/uploads/half-acre-daisy-cutter-pale-ale.jpg", description: "Our original hitter, a west coast Pale Ale chock-full of dank, aromatic hops, perfect for hoarding. 5.2% ABV - available year round."},
  {name: "Revolution Brewing Company", price: "$9.99", image: "https://www.eataly.com/wp/wp-content/uploads/2015/12/revolution_fist-city.jpg", description: "A blend of Centennial, Citra, Chinook, Cascade and Crystal hops give the beer its flavor and aroma."},
  {name: "Spiteful Brewing - Spiteful IPA", price: "$10.99", image: "https://s-media-cache-ak0.pinimg.com/736x/40/82/c9/4082c9b82d05d10ada2a843a10f60256.jpg", description: "This IPA is short and sweet: A wonderful India Pale Ale Brewed with El Dorado hops."},
  {name: "Temperance Beer Co. - Greenwood Beach", price: "10.99", image: "http://www.glunzbeers.com/wp-content/uploads/2015/10/Greenwood-Logo.jpg", description: "Greenwood Beach Blonde ale embraces summer with a bold addition of pineapple. It’s a beer for the opportunities you don’t pass up. Greenwood Beach Blonde ale embraces summer with a bold addition of pineapple. It’s a beer for the opportunities you don’t pass up. Greenwood Beach Blonde ale embraces summer with a bold addition of pineapple. It’s a beer for the opportunities you don’t pass up. Greenwood Beach Blonde ale embraces summer with a bold addition of pineapple. It’s a beer for the opportunities you don’t pass up. Greenwood Beach Blonde ale embraces summer with a bold addition of pineapple. It’s a beer for the opportunities you don’t pass up. Greenwood Beach Blonde ale embraces summer with a bold addition of pineapple. It’s a beer for the opportunities you don’t pass up. Greenwood Beach Blonde ale embraces summer with a bold addition of pineapple. It’s a beer for the opportunities you don’t pass up. Greenwood Beach Blonde ale embraces summer with a bold addition of pineapple. It’s a beer for the opportunities you don’t pass up. Greenwood Beach Blonde ale embraces summer with a bold addition of pineapple. It’s a beer for the opportunities you don’t pass up.Greenwood Beach Blonde ale embraces summer with a bold addition of pineapple. It’s a beer for the opportunities you don’t pass up.Greenwood Beach Blonde ale embraces summer with a bold addition of pineapple. It’s a beer for the opportunities you don’t pass up. Greenwood Beach Blonde ale embraces summer with a bold addition of pineapple. It’s a beer for the opportunities you don’t pass up. Greenwood Beach Blonde ale embraces summer with a bold addition of pineapple. It’s a beer for the opportunities you don’t pass up. Greenwood Beach Blonde ale embraces summer with a bold addition of pineapple. It’s a beer for the opportunities you don’t pass up. Greenwood Beach Blonde ale embraces summer with a bold addition of pineapple. It’s a beer for the opportunities you don’t pass up."},
  {name: "Lagunitas Brewing Company -  A Little Sumpin' Sumpin'", price: "$9.99", image: "http://www.brewhead.com/wp-content/uploads/2014/10/lagunitas_little_sumpin.jpg", description: "A truly unique style featuring a strong hop finish on a silky body."},
  {name: "3 Floyds Brewing Co. - Gumballhead", price: "$11.99", image: "http://4.bp.blogspot.com/-LDTs16AjoqQ/UdHawxcJXEI/AAAAAAAAByo/rRHhRRBOwNQ/s555/Three+Floyds+Gumballhead.jpg", description: "An American wheat beer with a refreshing, crisp citrus finish. This delicious session beer is brewed with boatloads of Amarillo hops."},
  {name: "Revolution Brewing Company - Anti-Hero IPA", price: "$8.99", image: "http://revbrew.com/_assets/uploads/Beer/beer_full_antiheroipa.jpg", description: "This iconic ale features a blend of four hop varieties which creates a crisp bitterness and imparts massive floral and citrus aromas."}
])
